force-app/main/default/objects/Transaction_Item__c/Transaction_Item__c.object-meta.xml
<CustomObject>
    <description>This object is used to store each items for a transaction</description>
    <label>Transaction Item</label>
    <nameField>
        <label>Transaction Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Item__c/fields/Item_Cost__c.field-meta.xml
<CustomField>
    <fullName>Item_Cost__c</fullName>
    <description>This field is used ot store the code t the transaction item. This field can get populated from REST API request as well</description>
    <label>Item Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TransactionItemDataPayload.cls
public class TransactionItemDataPayload{

    public Key keys {get; set;}
    public Value values {get; set;}
    
    private class Key{
        private String TransactionItemID {get; set;}
        
        private Key(Transaction_Item__c transactionItemRecord){
            this.TransactionItemID = transactionItemRecord.Id;
        }
    }
    
    private class Value{
        private String ItemCost {get; set;}
        private String ItemName {get; set;}
        
        private Value(Transaction_Item__c transactionItemRecord){
            this.ItemCost = String.valueOf(transactionItemRecord.Item_Cost__c);
            this.ItemName = transactionItemRecord.Name;
        }
    }
    
    public TransactionItemDataPayload(Transaction_Item__c transactionItemRecord){
        this.keys = new Key(transactionItemRecord);
        this.values = new Value(transactionItemRecord);
    }
}