force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>This object is to track the details for each transaction record</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TN-{000000000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to store the total cost of all the items stored under a transaction record.</description>
    <label>Total Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Total_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount__c</fullName>
    <description>This field is used to store the total discounts for all the items under the parent transaction record.</description>
    <label>Total Discount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>This field is used to store the time stamp of the transaction date</description>
    <label>Transaction Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TransactionDataPayload.cls
public class TransactionDataPayload{

    public Key keys {get; set;}
    public Value values {get; set;}
    
    private class Key{
        private String TransactionID {get; set;}
        
        private Key(Transaction__c transactionRecord){
            this.TransactionID = transactionRecord.Id;
        }
    }
    
    private class Value{
        private String TotalCost {get; set;}
        private String TotalDiscount {get; set;}
        private String TransactionDate {get; set;}
        
        private Value(Transaction__c transactionRecord){
            this.TotalCost = String.valueOf(transactionRecord.Total_Cost__c);
            this.TotalDiscount = String.valueOf(transactionRecord.Total_Discount__c);
            this.TransactionDate = String.valueOf(transactionRecord.Transaction_Date__c);
        }
    }
    
    public TransactionDataPayload(Transaction__c transactionRecord){
        this.keys = new Key(transactionRecord);
        this.values = new Value(transactionRecord);
    }
}